### ISSUE TITLE
Update readme to explain what verifiers-for-hyle does

### ISSUE THREAD

**Issue by s0lness** [Hyle-org/verifiers-for-hyle#7]
The purpose of this issue is to 
- write a good description of what the repo does, in the readme directly. This repo lists all the different verifiers that Hylé supports
- explain the code structure (each new verifier is a new folder)
- add links for hylé at the bottom: Useful links
- [Hylé website](https://www.hyle.eu/)
- [Hylé documentation](https://docs.hyle.eu/)

**Comment by petersdt** [comment]
Hi @s0lness  can I work on this ?

**Comment by No-bodyq** [comment]
Can I hop on this

**Comment by mariocodecr** [comment]
@s0lness  Hello team! 👋 I'm eager to contribute to the project by updating the README to provide clear explanations about the functionality of verifiers-for-hyle.

To address this issue, I'll begin by thoroughly reviewing the existing README to understand the project's scope and purpose. Then, I'll update the documentation to include a concise yet comprehensive explanation of what verifiers-for-hyle does. This will involve describing its main features, use cases, and how it integrates with other components of the project.

I'll ensure that the README is user-friendly, informative, and helps both newcomers and experienced users understand the role of verifiers-for-hyle in the project.

Looking forward to making a meaningful contribution!

Best regards,
Mario Araya

**Comment by od-hunter** [comment]
@s0lness Can I work on this please?

**Comment by od-hunter** [comment]
Hi @s0lness I’m still waiting to be assigned this issue. Assign me please. I can update the readme to make it easily understandable and technically accurate, estimated time of delivery is 24 hours and I’ll create a pr within 12 hours once assigned, thank you.

**Comment by rishabhRsinghvi** [comment]
Hi, please check my Pull Request.
#18 

Do tell me what I should improve to make it better.

**Comment by jedstroke** [comment]
@s0lness Let me take on this

**Comment by od-hunter** [comment]
@s0lness please can I be assigned this issue?

**Comment by mimiprosper** [comment]
Hi am a Frontend Dev, Smart Contract Dev and Technical Writer. Am currently studying Smart Contract Auditing. I have written articles: https://medium.com/@emma.onyedika.okeke

I have made successful documentation contribution for Starknet Scaffold in OD Hack project last month. 
 I can do the same for you Sir. https://github.com/horuslabsio/Starknet-Scaffold/commits?author=mimiprosper

I would write a good documentation following the guide lines given above. Thanks.

My Repo: https://github.com/mimiprosper

**Comment by Ternder001** [comment]
Hello Team Lead, am a web3 developer and i will love to be part of this project if given the opportunity.
https://github.com/Ternder001

**Comment by Ternder001** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
My recent focus in Ethereum-Solidity and Starknet-Cairo has significantly deepened my understanding of web3 technologies, positioning me well to contribute to innovative projects in the blockchain space. As an alumnus of Web3Bridge, where I received training in Solidity and Cairo, I have developed a solid foundation in these technologies. I am eager to contribute to open-source projects within the Starknet ecosystem, and I am particularly excited about the opportunity to make meaningful contributions to this project. Given the chance, I am committed to delivering my best work and leveraging my skills to drive success.

### How I plan on tackling this issue
I will approach the problem by creating  a comprehensive README for the Hylé Verifiers repository, the following steps will be taken:
1.	Understand the Purpose and Functionality of Hylé:
o	Ensure a clear understanding of Hylé’s role as a minimal layer one blockchain focused on verifying zero-knowledge proofs.
o	Understand how the verifiers fit into the broader Hylé ecosystem and their importance in enabling off-chain applications.
2.	Structure the README:
o	Create a clear and concise structure for the README to cover all necessary aspects: repository description, code structure, and useful links.
3.	Draft Repository Description:
o	Write a brief, engaging overview of what the repository does, highlighting the importance of ZKP verifiers and their integration with Hylé.
4.	Detail Code Structure:
o	Explain how the code is organized within the repository.
o	Describe the purpose of each folder and how new verifiers should be added.
5.	Add Useful Links:
o	Include direct links to the Hylé website and Hylé documentation for easy access to additional information and resources.
6.	Review and Refine:
o	Review the README for clarity, completeness, and accuracy.
o	Refine the language to ensure it is easy to understand and free of jargon.
Detailed Steps
1.	Repository Description:
o	Introduce Hylé and its core function of verifying zero-knowledge proofs.
o	Explain the purpose of the repository: listing all the different verifiers that Hylé supports.
o	Highlight the benefits of using Hylé and its verifiers for off-chain applications with blockchain security.
2.	Code Structure:
o	Describe the overall structure of the repository.
o	For each verifier, mention that it has its own folder containing all necessary files and documentation.
o	Provide an example of the folder structure and what each component within the folders represents.
3.	Useful Links:
o	Add a section at the end of the README titled "Useful Links".
o	Include hyperlinks to the Hylé website and Hylé documentation for users who want to learn more or need further assistance.

**Comment by codeZe-us** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
Full Stack Mobile Engineer leveraging Golang as a backend technology while building mobile applications with Flutter, SwiftUI and Kotlin JetPack Compose

### How I plan on tackling this issue
1. Understand the project structure and architecture.
2. Navigate between folders in the project to get a full knowledge of what it holds and how they communicate between folders which holds files.
3. Add important links.

**Comment by s0lness** [comment]
Closed this issue because it's not relevant anymore.
