### ISSUE TITLE
Implement a Noir Barretenberg verifier

### ISSUE THREAD

**Issue by wraitii** [Hyle-org/verifiers-for-hyle#8]
See https://github.com/Hyle-org/hyle/issues/24

This PR will be merged alongside that one.

**Comment by Gerson2102** [comment]
Hey guys. I would like to try this one :). I'm Gerson, participating in the ODHack 4.0, check my OD profile: https://app.onlydust.com/u/Gerson2102

**Comment by wraitii** [comment]
Hey @Gerson2102 , see https://github.com/Hyle-org/hyle/issues/24 .
You can try and help there or pick another issue

**Comment by Gerson2102** [comment]
@wraitii Why? This not a beginner friendly issue?

**Comment by wraitii** [comment]
@Gerson2102  the issues are paired, so one person will necessary handle both

**Comment by Gerson2102** [comment]
@wraitii that is something that we have to implement here, in this repo? To see which repo do we have to set up.

**Comment by Gerson2102** [comment]
And to see code por examples or something to guide me a little bit.

**Comment by wraitii** [comment]
Done in #15
