### ISSUE TITLE
Implement a MidenVM Verifier

### ISSUE THREAD

**Issue by wraitii** [Hyle-org/verifiers-for-hyle#9]
See https://github.com/Hyle-org/hyle/issues/25

This issue will be closed alongside the other one.

**Comment by od-hunter** [comment]
Hello @wraitii can I be assigned this issue? I’m ready to work.

**Comment by Bosun-Josh121** [comment]
Still available? I can work on this

**Comment by wraitii** [comment]
Sorry, this one is done actually.
